from tkinter import *
from tkinter import ttk,messagebox,font

def entry(t):
    t.destroy()
    t=Tk()
    t.geometry("1000x1000")
    t.title("Customer Entry")
    t.attributes("-fullscreen",True)
    F1=Frame(t,height=100,width=1500,bg="#698B69").pack()
    Lf = font.Font(weight="bold", family="Times New Roman", size=35)
    L1=Label(F1,text="Data Entry",fg="white",font=Lf,bg="#698B69").place(relx=0.42,rely=0.02)
    F2=Frame(t,height=600,width=550,bg="#97FFFF")
    Lf = font.Font(weight="bold", family="Times New Roman", size=30)
    L2=Label(F2,text="Customer Details",fg="#483D8B",font=Lf,bg="#97FFFF").place(relx=0.22,rely=0.02)
    Lf = font.Font(weight="bold", family="Times New Roman", size=20)
    L3=Label(F2,text="Name : ",fg="black",font=Lf,bg="#97FFFF").place(relx=0.05,rely=0.15)
    L4=Label(F2,text="Account number : ",fg="black",font=Lf,bg="#97FFFF").place(relx=0.05,rely=0.3)
    L5=Label(F2,text="Adhaar number : ",fg="black",font=Lf,bg="#97FFFF").place(relx=0.05,rely=0.45)
    L6=Label(F2,text="PAN number : ",fg="black",font=Lf,bg="#97FFFF").place(relx=0.05,rely=0.6)
    L7=Label(F2,text="Min balance in rupees : ",fg="black",font=Lf,bg="#97FFFF").place(relx=0.05,rely=0.75)
    E1=Entry(F2)
    E1.place(relx=0.62,rely=0.17)
    E2=Entry(F2)
    E2.place(relx=0.62,rely=0.32)
    E3=Entry(F2)
    E3.place(relx=0.62,rely=0.47)
    E4=Entry(F2)
    E4.place(relx=0.62,rely=0.62)
    L8=Label(F2,font=Lf,bg="#97FFFF",fg="black",text="1000").place(relx=0.62,rely=0.75)
    Lf = font.Font(weight="bold", family="Times New Roman", size=20)
    def save():
        s="\n"+E1.get()+"\t"+E2.get()+"\t"+E3.get()+"\t"+E4.get()+"\t"+"1000"
        file=open("customer.txt","a")
        file.write(s)
        E1.delete(0,END)
        E2.delete(0,END)
        E3.delete(0,END)
        E4.delete(0,END)
        messagebox.showinfo("Success","Successfully inserted...!")
    B1=Button(F2,text="Submit",bg="#8B814C",fg="black",font=Lf,command=save).place(relx=0.61,rely=0.87)
    F2.place(relx=0.01,rely=0.18)

    #creating a tree
    tree=ttk.Treeview(t,columns=("Name","Account number","Adhaar number","PAN number","Minimum balance in rupees"),show="headings")
    tree.heading("#1",text="Name")
    tree.heading("#2",text="Account number")
    tree.heading("#3",text="Adhaar number")
    tree.heading("#4",text="PAN number")
    tree.heading("#5",text="Minimum balance in rupees")
    tree.place(relx=0.42,rely=0.18,height=570)
    tree.column("#1",width=85)
    tree.column("#2",width=160)
    tree.column("#3",width=160)
    tree.column("#4",width=160)
    tree.column("#5",width=200)
    Lf = font.Font(weight="bold", family="Times New Roman", size=15)
    def read():
        try:
            f=open("customer1.txt","r")
            r=f.readlines()
            for x in r:
                z=x.split("\t")
                tree.insert("","end",values=z)
        except FileNotFoundError:
            tree.insert("","end",values=("File not found",))
    B2=Button(t,text="Finish",font=Lf,bg="black",fg="white",command=read).place(relx=0.7,rely=0.93)
    t.mainloop()
def login(a,b,t):
    if(a=="admin" and b=="1234"):
        entry(t)
    else:
        admin(t)

def admin(t):
    t.destroy()
    t=Tk()
    t.geometry("1000x1000")
    t.title("Admin Login")
    t.attributes("-fullscreen", True)
    Lf = font.Font(weight="bold", family="Times New Roman", size=35)
    F1 = Frame(t, height=100, width=1500, bg="#FFB90F")
    F1.pack()
    L4 = Label(F1, text="Senthil Bank", font=Lf, fg="black", bg="#FFB90F")
    L4.place(relx=0.42, rely=0.3)
    F2 = Frame(t, height=100, width=1500, bg="#FFB90F")
    F2.place(relx=0.0, rely=0.9)
    L5 = Label(F2, text="Contact info : 9943371822 ", font=Lf, fg="black", bg="#FFB90F")
    L5.place(relx=0.3, rely=0.1)
    F3 = Frame(t, height=500, width=500, bg="#E6E6FA")
    F3.place(relx=0.33, rely=0.2)
    Lf = font.Font(weight="bold", family="Times New Roman", size=20)
    L1 = Label(F3, text="Admin Login", font=Lf, fg="#DC143C")
    L1.place(relx=0.33, rely=0.01)
    L2 = Label(F3, text=" User name : ", font=Lf, bg="#E6E6FA")
    L2.place(relx=0.1, rely=0.3)
    L3 = Label(F3, text=" Password : ", font=Lf, bg="#E6E6FA")
    L3.place(relx=0.1, rely=0.5)
    E1 = Entry(F3)
    E1.place(relx=0.45, rely=0.322)
    E2 = Entry(F3)
    E2.place(relx=0.45, rely=0.522)
    Lf=font.Font(weight="bold",family="Times New Roman",size=18)
    B1=Button(F3,font=Lf,text="Submit",bg="white",fg="red",command=lambda:login(E1.get(),E2.get(),t)).place(relx=0.40,rely=0.75)
    t.mainloop()

def employee(t):
    t.destroy()
    t=Tk()
    t.geometry("1000x1000")
    t.title("Employee Login")
    t.attributes("-fullscreen",True)
    Lf=font.Font(weight="bold",family="Times New Roman",size=35)
    F1=Frame(t,height=100,width=1500,bg="#8B4513")
    F1.pack()
    L4=Label(F1,text="Senthil Bank",font=Lf,fg="white",bg="#8B4513")
    L4.place(relx=0.42,rely=0.3)
    F2=Frame(t,height=100,width=1500,bg="#8B4513")
    F2.place(relx=0.0,rely=0.9)
    L5=Label(F2,text="Contact info : 9943371822 ",font=Lf,fg="white",bg="#8B4513")
    L5.place(relx=0.3,rely=0.1)
    F3=Frame(t,height=500,width=500,bg="#E6E6FA")
    F3.place(relx=0.33,rely=0.2)
    Lf=font.Font(weight="bold",family="Times New Roman",size=20)
    L1=Label(F3,text="Customer Login",font=Lf,fg="red")
    L1.place(relx=0.33,rely=0.01)
    L2=Label(F3,text=" User name : ",font=Lf,bg="#E6E6FA")
    L2.place(relx=0.1,rely=0.3)
    L3=Label(F3,text=" Password : ",font=Lf,bg="#E6E6FA")
    L3.place(relx=0.1,rely=0.5)
    E1=Entry(F3)
    E1.place(relx=0.45,rely=0.322)
    E2=Entry(F3)
    E2.place(relx=0.45,rely=0.522)
    Lf=font.Font(weight="bold",family="Times New Roman",size=20)
    B1=Button(F3,text="Admin Login",bg="#E6E6FA",fg="#8B4513",font=Lf,command=lambda:admin(t))
    B1.place(relx=0.35,rely=0.8)
    Lf=font.Font(weight="bold",family="Times New Roman",size=12)
    B2=Button(F3,font=Lf,text="Submit",bg="white",fg="red").place(relx=0.48,rely=0.65)
    t.mainloop()

#Home page
t=Tk()
t.title("Senthil bank")
t.geometry("1000x1000")
t.attributes("-fullscreen",True)
F1=Frame(t,height=100,width=10000,bg="green")
F1.pack()
Lf=font.Font(weight="bold",family="Times New Roman",size=30)
L1=Label(F1,text="SENTHIL BANK",bg="white",font=Lf)
L1.config(bg="green",fg="white")
L1.place(relx=0.4,rely=0.03)


Lf=font.Font(weight="bold",family="Times New Roman",size=20)
s="""This banking facility provides loans for those who are trying
  to start up their own Business. we are provide loans for those who want to
  study in foreigh countries"""
L2=Label(t,text=s,font=Lf)
L2.place(relx=0.2,rely=0.2)
B1=Button(t,text="Admin or Customer login",font=Lf,bg="#FFE4C4",fg="#8A360F",command=lambda:employee(t))
B1.place(relx=0.4,rely=0.35)

F2=Frame(t,height=100,width=1500,bg="green")
Lf=font.Font(weight="bold",family="Times New Roman",size=25)
L3=Label(F2,text="CONTACT : 9943371822",font=Lf)
L3.config(bg="green",fg="white")
L3.place(relx=0.35,rely=0.2)
F2.place(relx=0.0,rely=0.9)

Lf=font.Font(weight="bold",family="Times New Roman",size=20)
a="""Senthil bank offers different types of account to meet your financial goals
     and secure your future. Choose from your wide range of deposit products that are
     specifically designed to keep your unique requirements in mind. """
L4=Label(text=a,font=Lf)
L4.place(relx=0.2,rely=0.46)
B2=Button(t,text="Savings account",font=Lf,bg="#FFE4C4",fg="#8A360F")
B2.place(relx=0.28,rely=0.6)
B3=Button(t,text="Current account",font=Lf,bg="#FFE4C4",fg="#8A360F")
B3.place(relx=0.6,rely=0.6)


F3=Frame(t,height=100,width=1000,bg="#E6E6FA")
F3.place(relx=0.14,rely=0.7)
Lf=font.Font(weight="bold",family="Times New Roman",size=20)
b="""Exclusive offers : Gain access to many exciting offers
     and trending deals on senthil debit and credit cards """
L5=Label(F3,text=b,font=Lf)
L5.config(bg="#E6E6FA",fg="#292421")
B4=Button(F3,text="View Offers",bg="#F0E68C",font=Lf,fg="#DC143C")
B4.place(relx=0.8,rely=0.2)
L5.place(relx=0.1,rely=0.15)

F4=Frame(t,height=400,width=280,bg="#E6E6FA")
F4.place(relx=0.0,rely=0.15)
Lf=font.Font(weight="bold",family="Times New Roman",size=18)
B5=Button(F4,text="Accounts",bg="#FFE4C4",fg="#8A360F",font=Lf)
B5.place(relx=0.1,rely=0.1)
B6=Button(F4,text="Loans",bg="#FFE4C4",fg="#8A360F",font=Lf)
B6.place(relx=0.1,rely=0.3)
B7=Button(F4,text="Investments",bg="#FFE4C4",fg="#8A360F",font=Lf)
B7.place(relx=0.1,rely=0.5)
B8=Button(F4,text="Insurance",bg="#FFE4C4",fg="#8A360F",font=Lf)
B8.place(relx=0.1,rely=0.7)
t.mainloop()
